<?php
/**
 * @file
 * Code for the Amani: Activity feature.
 */

include_once 'amani_activity.features.inc';

/**
 * Node preprocessor.
 */
function amani_activity_preprocess_node(&$vars) {

  if ($vars['type'] == 'activity') {
    // Alter field_program display on activity nodes.
    $title = t('< Back to !title', array('!title' => $vars['field_program'][0]['entity']->title));
    $path = 'node/' . $vars['field_program'][0]['entity']->nid;
    $vars['content']['field_program'][0]['#markup'] = l($title, $path);
  }
}