<?php

/**
 * Implements hook_block_view_alter().
 */
function amani_custom_block_view_alter(&$data, $block) {
  switch($block->bid) {
    case "system-main-menu":
    case "menu-menu-amani-main-menu":
    case "menu-menu-meta":
    case "menu-menu-social-media":
    case "superfish-1":
    case "284":
    case 'locale-language':
      // Remove the title from the menu block.
      $data['subject'] = '';
      break;
  }
}