<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'amani_media_gallery.features.inc';

/**
 * Implements hook_menu().
 */
function amani_media_gallery_menu() {
  $items = array();

  $items['gallery'] = array(
    'title' => t('Gallery'),
    'description' => '',
    'page callback' => 'amani_media_gallery_list_galleries',
    'access arguments' => array('access content'),
  );

  return $items;
}

function amani_media_gallery_list_galleries() {
  $vocab = taxonomy_vocabulary_machine_name_load('gallery_collections');
  $tids = taxonomy_get_tree($vocab->vid);
  module_load_include('inc', 'media_gallery', 'media_gallery.pages');
  return media_gallery_list_galleries(taxonomy_term_load($tids[0]->tid));
}

/**
 * Preprocessor for media_gallery_meta.
 */
function amani_media_gallery_preprocess_media_gallery_meta(&$variables) {

  // Add date to the gallery description.
  $parts = explode('/', $variables['link_path']);
  if (is_numeric($parts[1]) && $gallery_node = node_load($parts[1])) {
    $date = format_date($gallery_node->created, 'custom', 'F j, Y');
    $variables['description'] = $variables['description'] . ' | <span>Added ' . $date . '</span>';
  }
}