<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'amani_event.features.inc';

/**
 * Implements hook_default_fields_alter().
 */
function amani_event_field_default_fields_alter(&$fields) {
  // Adjust weights to fix order on node form
  if (isset($fields['node-event-field_event_type'])) {
    $fields['node-event-field_event_type']['field_instance']['widget']['weight'] = '15';
  }
  if (isset($fields['node-event-field_tags'])) {
    $fields['node-event-field_tags']['field_instance']['widget']['weight'] = '17';
  }
  if (isset($fields['node-event-body'])) {
    $fields['node-event-body']['field_instance']['widget']['weight'] = '10';
    $fields['node-event-body']['field_instance']['label'] = 'Description';
  }
}