<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_default_fields_alter().
 */
function amani_blog_field_default_fields_alter(&$fields) {
  foreach ($fields as $key => &$field) {
    if ($key == 'node-blog-field_content_image') {
      // Override field_content_image to use image widget.
      $field['field_instance']['widget']['module'] = 'image';
      $field['field_instance']['widget']['type'] = 'image_image';
      $field['field_instance']['widget']['settings'] = array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      );
      // Set file directory and alt field.
      $field['field_instance']['settings'] = array(
        'alt_field' => 1,
        'default_image' => 0,
        'file_directory' => 'team-field_team_image',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '',
        'max_resolution' => '',
        'min_resolution' => '',
        'title_field' => 0,
        'user_register_form' => FALSE,
      );
    }
  }
}