<?php
/**
 * @file
 * Code for the Amani: Incident report feature.
 */

include_once 'amani_incident_report.features.inc';

/**
 * Implements hook_field_formatter_info().
 */
function amani_incident_report_field_formatter_info() {
  return array(
    'amani_address_city' => array(
      'label' => t('Address: display city only'),
      'description' => t('Addressfield: Display city only'),
      'field types' => array('addressfield'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function amani_incident_report_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'amani_address_city':
      foreach ($items as $delta => $item) {
        $element[$delta]['locality'] = array(
          '#markup' => $item['locality'],
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_widget_form_alter().
 *
 * Make the geocoder address lookup button text more intuitive.
 */
function amani_incident_report_field_widget_form_alter(&$element, &$form_state, $context){
  if (is_array($element) && isset($element[0]) && is_array($element[0])){
    if (isset($element[0]['use_geocoder']) && is_array($element[0]['use_geocoder'])){
      if (isset($element[0]['use_geocoder']['#value'])){
        $element[0]['use_geocoder']['#value'] = t('Find Address on Map');
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function amani_incident_report_form_incident_report_node_form_alter(&$form, &$form_state, $form_id) {
  // Ensure we use the labels from config on map records - if they exist.
  if ($title = variable_get('incident-map-filter-field_incident_report_type-category-title')) {
    $form['field_incident_report_type'][LANGUAGE_NONE]['#title'] = $title;
  }
  if ($title = variable_get('incident-map-filter-field_incident_severity-category-title')) {
    $form['field_incident_severity'][LANGUAGE_NONE]['#title'] = $title;
  }
  if ($title = variable_get('incident-map-filter-field_map_filter_3-category-title')) {
    $form['field_map_filter_3'][LANGUAGE_NONE]['#title'] = $title;
  }
  if ($title = variable_get('incident-map-filter-field_map_filter_4-category-title')) {
    $form['field_map_filter_4'][LANGUAGE_NONE]['#title'] = $title;
  }
}

/**
 * Implements hook_node_view().
 */
function amani_incident_report_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'incident_report') {
    // Ensure we use the labels from config on map record node displays - if they exist.
    if ($title = variable_get('incident-map-filter-field_incident_report_type-category-title')) {
      $node->content['field_incident_report_type']['#title'] = $title;
    }
    if ($title = variable_get('incident-map-filter-field_incident_severity-category-title')) {
      $node->content['field_incident_severity']['#title'] = $title;
    }
    if ($title = variable_get('incident-map-filter-field_map_filter_3-category-title')) {
      $node->content['field_map_filter_3']['#title'] = $title;
    }
    if ($title = variable_get('incident-map-filter-field_map_filter_4-category-title')) {
      $node->content['field_map_filter_4']['#title'] = $title;
    }
  }
}
