<?php
/**
 * @file
 * Code for the Amani: Front page feature.
 */

include_once 'amani_front_page.features.inc';

/**
 * Page preprocessor.
 */
function amani_front_page_preprocess_page(&$vars) {

  // Do not display title on homepage.
  if ($vars['is_front']) {
    drupal_set_title('');
  }
}

/**
* Implements hook_block_info().
*/
function amani_front_page_block_info() {
  $blocks = array();
  $blocks['special_event'] = array(
    'info' => t('Special Event / Feature Callout'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function amani_front_page_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'special_event' :
      $block['content'] = special_event_view();
      break;
  }
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function special_event_view() {
  $block = array();

  // Capture WYSIWYG text from the variable
  $text = variable_get('text_variable', '');

  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => $text,
      '#suffix' => '',
    ),
  );
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function amani_front_page_block_configure($delta='') {
  $form = array();
  switch($delta) {
    case 'special_event' :
      // Text field form element
      $form['text_body'] = array(
        '#type' => 'text_format',
        '#title' => t('Enter your text here in WYSIWYG format'),
        '#default_value' => variable_get('text_variable', ''),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function amani_front_page_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'special_event' :
      // Saving the WYSIWYG text
      variable_set('text_variable', $edit['text_body']['value']);
      break;
  }
}
