<?php
/**
 * @file
 * Code for the amani_partners feature.
 */

include_once 'amani_partners.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function amani_partners_entity_info_alter(&$entity_info) {

  // Create a view mode for partner images that may come
  // in different sizes and aspect ratios.
  $entity_info['file']['view modes']['partner_logo'] = array(
    'label' => t('Partner logo'),
    'custom settings' => TRUE,
  );
}