<?php

include_once('amani_custom.inc');
/**
 * Implements hook_block_view_alter().
 */
function amani_custom_block_view_alter(&$data, $block) {

  if (isset($block->bid)) {
    switch($block->bid) {
      case "system-main-menu":
      case "menu-menu-amani-main-menu":
      case "menu-menu-meta":
      case "menu-menu-social-media":
      case "284":
      case 'locale-language':
        // Remove the title from the menu block.
        $data['subject'] = '';
        break;
      case "superfish-1":
        $data['subject'] = '';
        // Add mobile menu link.
        $data['content'] = '<div class="mobile-menu-link"><a href="#">' . t('Menu') . '</a></div>' . $data['content'];
        //krumo($data);
        break;
    }
  }
}

/**
 * Implements hook_block_info_alter().
 */
function amani_custom_block_info_alter(&$blocks, $theme, $code_blocks) {

  // Make sure the main page content displays above any blocks added to
  // the content region in a context.
 $blocks['system']['main']['weight'] = -40;
}

/**
 * Implements hook_form_alter().
 */
function amani_custom_form_alter(&$form, &$form_state, $form_id) {
  switch($form_id) {
    case 'views_exposed_form':
      if ($form['#id'] == 'views-exposed-form-team-page') {
          $form['field_team_contact_type_value']['#options']['All'] = t('our team') . '...';
      }
      break;
    case 'incident_report_node_form':
      $form['field_incident_report_type'][LANGUAGE_NONE]['#title'] = variable_get('incident-map-filter-field_incident_report_type-category-title', 'Filter 1 title');
      $form['field_incident_severity'][LANGUAGE_NONE]['#title'] = variable_get('incident-map-filter-field_incident_severity-category-title', 'Filter 2 title');
      break;
    default:
      break;
  }
}

/**
 * Implementes hook_file_type().
 *
 * There appears to be a bug with media_youtube which stops you from uploading
 * videos from youtube due to validation errors see
 * https://www.drupal.org/node/1245686.
 */
function amani_custom_file_type($file) {
  if($file->filemime == 'video/youtube') {
    return array('video');
  }
}
