<?php 

/**
 * Implments hook_menu().
 */
function amani_sms_menu() {
  $items['sms'] = array(
    'page callback' => 'amani_sms_endpoint',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Gets the messages(SMSs) sent by SMSsync as a POST request.
 *
 */
function amani_sms_endpoint() {
  $error = NULL;
  // Set success to false as the default success status
  $success = true;

  if ($message = $_POST['message']) {
    // save to body field on page content type.
    $entity_type = 'page';
    $entity = entity_create($entity_type, array('title' => 'test', 'body' => $message));
    entity_save($entity_type, $entity);
  }

  $response = array(
    'payload' => array(
      'success' => $success,
      'error'   => $error
    )
  );

  return drupal_json_output($response);
}

