<?php 

/**
 * Implments hook_menu().
 */
function amani_sms_menu() {
  $items['sms'] = array(
    'page callback' => 'amani_sms_endpoint',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Gets the messages(SMSs) sent by SMSsync as a POST request.
 *
 */
function amani_sms_endpoint() {
  $error = NULL;
  // Set success to false as the default success status
  $success = true;

  if ($message = $_POST['message']) {
    $entity = entity_create('node', array('type' =>'page'));
    $entity->title = "Testing";
    $entity->body = array(LANGUAGE_NONE => array(0 => array('value' => "Howdy Partner!")));
    entity_save('node', $entity);
  }

  $response = array(
    'payload' => array(
      'success' => $success,
      'error'   => $error
    )
  );

  return drupal_json_output($response);
}

